JobPortalMVCApplication/Models/SearchJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace JobPortalMVCApplication.Models
{
    public class SearchJobController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: SearchJob
        public ActionResult searchjob_pageload()
        {
            var job = dbobj.tbl_Job.ToList();
            return View(job);
        }

        public ActionResult searchjob_click(JobSearch clsobj)
        {
            string qry = "";
            if(!string.IsNullOrWhiteSpace(clsobj.insertse.experience))
            {
                qry += " and Experience like '%" + clsobj.insertse.experience + "'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.skills))
            {
                qry += " and Skills like '%" + clsobj.insertse.skills + "'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.location))
            {
                qry += " and Loction like '%" + clsobj.insertse.location + "'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.posted_Date))
            {
                qry += " and PostedDate like '%" + clsobj.insertse.posted_Date + "'";
            }
            return View("searchjob_pageload",getdata1(clsobj,qry));
        }

        private JobSearch getdata1(JobSearch clsobj,string qry)
        {
            using(var con=new SqlConnection(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("[sp_Jobsearches]", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new JobSearch();
                while(dr.Read())
                {
                    var jobcls = new jsearch();
                   jobcls.companyId= Convert.ToInt32( dr["fk_CompanyId"].ToString());
                    jobcls.skills = dr["Skills"].ToString();
                    jobcls.experience = dr["Experience"].ToString();
                    jobcls.job_status = dr["JobStatus"].ToString();
                    jobcls.last_Date = dr["ApplyLastDate"].ToString();

                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

JobPortalMVCApplication/Controllers/ApplyCVController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;

namespace JobPortalMVCApplication.Controllers
{
    public class ApplyCVController : Controller
    {
        // GET: ApplyCV
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        public ActionResult ApplyCV_Load(int cid,int jid)
        {
            TempData["cid"] = cid;
            TempData["jid"] = jid;
            return View();
        }

        public ActionResult Applyclick_Load(CVInsert clsobj,JobSearch obj,HttpPostedFileBase file)
        {
            if(ModelState.IsValid)
            { 
                if(file.ContentLength>0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/Resume");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\Resume", fname);
                    clsobj.cv = fullpath;
                }
                dbobj.sp_applycv(Convert.ToInt32(Session["uid"].ToString()), Convert.ToInt32(TempData["id"]), clsobj.cv, DateTime.Now.ToString("yyyy-MM-dd"), "Applied");
                clsobj.appmsg = "APPLICATION SUBMITTED";
                return View("ApplyCV_Load",clsobj);
            }
            return View("ApplyCV_Load",clsobj);
        }
    }
}

JobPortalMVCApplication/Controllers/SearchJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace JobPortalMVCApplication.Models
{
    public class SearchJobController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: SearchJob
        public ActionResult searchjob_pageload()
        {
            //
           
            return View(Getdata());
        }

        public JobSearch Getdata()
        {
            var joblist = new JobSearch();

            List<string> lst = new List<string>();

            var job = dbobj.tbl_Job.ToList();
            foreach (var e in job)
            {
                var jobcls = new jsearch();
                jobcls.job_id = e.JobId;
                jobcls.companyId = e.fk_CompanyId;
                jobcls.skills = e.Skills;
                jobcls.experience = e.Experience;
                jobcls.job_status = e.JobStatus;
                jobcls.last_Date = e.ApplyLastDate;

                joblist.selectjob.Add(jobcls);

            }
            return joblist;
        }

        public ActionResult searchjob_click(JobSearch clsobj)
        {
            string qry = "";
            if(!string.IsNullOrWhiteSpace(clsobj.insertse.experience))
            {
                qry += " and Experience like '%" + clsobj.insertse.experience + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.skills))
            {
                qry += " and Skills like '%" + clsobj.insertse.skills + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.location))
            {
                qry += " and Loction like '%" + clsobj.insertse.location + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.posted_Date))
            {
                qry += " and PostedDate like '%" + clsobj.insertse.posted_Date + "%'";
            }
            return View("searchjob_pageload",getdata1(clsobj,qry));
        }

        private JobSearch getdata1(JobSearch clsobj,string qry)
        {
            using(var con=new SqlConnection(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_Jobsearches", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new JobSearch();
                while(dr.Read())
                {
                    var jobcls = new jsearch();
                   jobcls.companyId= Convert.ToInt32( dr["fk_CompanyId"].ToString());
                    jobcls.skills = dr["Skills"].ToString();
                    jobcls.experience = dr["Experience"].ToString();
                    jobcls.job_status = dr["JobStatus"].ToString();
                    jobcls.last_Date = dr["ApplyLastDate"].ToString();

                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

JobPortalMVCApplication/Views/SearchJob/searchjob_pageload.cshtml
@model JobPortalMVCApplication.Models.JobSearch
@{
    ViewBag.Title = "searchjob_pageload";
   // Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>JOB SEARCH APPLICATION</h1>
<div>
    <div class="container mt-5">
        <div class="card shadow-sm">
            <div class="card-header bg-primary text-white">
                <h4 class="mb-0">Job Search</h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("searchjob_click", "SearchJob", FormMethod.Post))
                {
                    {
                        <div class="row g-3">
                            <!-- Experience -->
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.insertse.experience)
                                    @Html.TextBoxFor(m => m.insertse.experience)
                                </div>
                            </div>

                            <!-- Skills -->
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.insertse.skills)
                                    @Html.TextBoxFor(m => m.insertse.skills)
                                </div>
                            </div>

                            <!-- Location -->
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.insertse.location)
                                    @Html.TextBoxFor(m => m.insertse.location)
                                </div>
                            </div>

                           
                            <!-- Search Button -->
                            <div class="d-flex justify-content-end mt-4">
                                <button type="submit" class="btn btn-primary">Search Jobs</button>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>

</div>
<br />
<br />
<br />

@using (Html.BeginForm("searchjob_pageload", "SearchJob", FormMethod.Get))
{
        <div class="container mt-5">
        <div class="card shadow">
            <div class="card-header bg-primary text-white">
                <h4 class="mb-0">Job Search Results</h4>
            </div>
            <div class="card-body">
               @if(Model!=null)
                {
                    if(Model.selectjob!=null && Model.selectjob.Count != 0)
                    {
                        <table class="table table-striped table-hover">
                            <thead class="table-dark">
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.insertse.companyId)</th>
                                    <th>@Html.DisplayNameFor(m => m.insertse.skills)</th>
                                    <th>@Html.DisplayNameFor(m => m.insertse.experience)</th>
                                    <th>@Html.DisplayNameFor(m => m.insertse.job_status)</th>
                                    <th>@Html.DisplayNameFor(m => m.insertse.last_Date)</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.selectjob)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem=> item.companyId)</td>
                                        <td>@Html.DisplayFor(modelItem => item.skills)</td>
                                        <td>@Html.DisplayFor(modelItem => item.experience)</td>
                                        <td>@Html.DisplayFor(modelItem => item.job_status)</td>
                                        <td>@Html.DisplayFor(modelItem => item.last_Date)</td>
                                        <td>
                                            @Html.ActionLink("Apply Now", "ApplyCV_Load", "ApplyCV",new { cid = item.companyId, jid = item.job_id },null)
                                        </td>
                                    </tr>
                                 }
                            </tbody>
                        </table>
                     }
                   else
                    {
                    <div class="alert alert-warning text-center" role="alert">
                        <strong>No jobs found!</strong> Please adjust your search criteria and try again.
                    </div>
                    }
                }
            </div>
         </div>
    </div>
                }