JobPortalMVCApplication/Controllers/CompanyRegistrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;

namespace JobPortalMVCApplication.Controllers
{
    public class CompanyRegistrationController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: CompanyRegistration
        public ActionResult CompanyReg_Pageload()
        {
            return View();
        }

        //public ActionResult Login()
        //{
        //    return View();
        //}


        public ActionResult InsertCompany_Click( InsertCompany insertCompany, HttpPostedFileBase file, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength>0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s=Server.MapPath("~/Company Photos/");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                     var fullpath=Path.Combine("~\\Company Photos" , fname);
                    insertCompany.photo = fullpath;
                }
                var maxLoginId=dbobj.sp_MaxLoginId().FirstOrDefault();
                int regId = 0;
                int maxId = Convert.ToInt32(maxLoginId);
                if (maxId==0)
                {
                    regId = 1;
                }
                else
                {
                    regId = maxId + 1;
                }
                dbobj.sp_RegisterCompany(regId, insertCompany.name, insertCompany.address, insertCompany.email, insertCompany.phone, insertCompany.website, insertCompany.photo);
                dbobj.sp_InsertLoginCredentials(regId, insertCompany.username, insertCompany.password, "Company");
                insertCompany.msg = "INSERTED SUCESSFULLY";
                return View("CompanyReg_Pageload", insertCompany);
                //return View("InsertCompany_Click",insertCompany);
            }
            return View("CompanyReg_Pageload", insertCompany);
        }
        
    }
}

JobPortalMVCApplication/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;


namespace JobPortalMVCApplication.Controllers
{
    public class LoginController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: Login
        public ActionResult Login_pageload()
        {
            return View();
        }
        public ActionResult login_click(LoginCls loginCls)
        {
            if (ModelState.IsValid)
            {
                var getId = dbobj.sp_CountLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                if (Convert.ToInt32(getId) == 1)
                {
                    var getRegId = dbobj.sp_GetLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                    Session["uid"] = getRegId;
                    string userType = dbobj.sp_LoginType(loginCls.username, loginCls.password).FirstOrDefault();
                    if (userType == "Company")
                    {
                        return RedirectToAction("AdminHome");
                    }
                    else if (userType == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    loginCls.msg = "INVALID USERNAME OR PASSWORD";
                    return View("Login_pageload", loginCls);
                }
            }
            return View("Login_pageload", loginCls);
        }
        public ActionResult AdminHome()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            var job = dbobj.tbl_Job.ToList();
            return View(job);
            //  var jobs=dbobj.sp_fetchAllJobDetails();
           // return View(jobs);
        }
    }
}

JobPortalMVCApplication/Views/CompanyRegistration/CompanyReg_Pageload.cshtml
@model JobPortalMVCApplication.Models.InsertCompany
@{
    ViewBag.Title = "CompanyReg_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>COMPANY REGISTRATION</h1>
<div>
    @using(Html.BeginForm("InsertCompany_Click", "CompanyRegistration", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div><label>NAME: </label></div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div><label>ADDRESS: </label></div>
        <div>
            @Html.TextAreaFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)



        </div>
        <div><label>PHONE: </label></div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>
        <div><label>EMAIL: </label></div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div><label>WEBSITE ADDRESS : </label></div>
        <div>
            @Html.TextBoxFor(m => m.website)
            @Html.ValidationMessageFor(m => m.website)
        </div>
        <div><label>PHOTO: </label></div>
        <div>
            @Html.TextBox("file", " ", new { Type = "file" })
            @Html.ValidationMessageFor(m => m.photo)
        </div>
        <div><label> USERNAME : </label></div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>
        <div><label>PASSWORD : </label></div>
        <div>
            @Html.PasswordFor(m => m.password)
            @Html.ValidationMessageFor(m => m.password)
        </div>
        <div><label>CONFIRM PASSWORD : </label></div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div><input type="submit" value="Insert"/>
               @Html.DisplayFor(m=>m.msg)
        </div>
        


    }
</div>

JobPortalMVCApplication/Views/CompanyRegistration/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LOGIN USER</h2>
<div>
    @using(Html.BeginForm("","",))
</div>