JobPortalMVCApplication/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;

namespace JobPortalMVCApplication.Controllers
{
    public class JobController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: Job
        public ActionResult JobInsert_Pageload()
        {
            return View();
        }
        public ActionResult JobInsert_Click(InsertJobs clsobj)
        {
            if (ModelState.IsValid)
            {
                int userId = Convert.ToInt32(Session["uid"]);
                string Date = DateTime.Now.ToString("yyyy-MM-dd");
                dbobj.sp_InsertJobOpenings(userId, clsobj.jobTitle, clsobj.jobDesp, clsobj.jobSkills, clsobj.jobExp, clsobj.jobSalary, clsobj.jobLoc,  clsobj.jobStatus, clsobj.jobLastDate,Date);
              //  insert into tbl_Job values(@Cid, @jobTitle, @jobDes, @skill, @exp, @sal, @loc, @jobStatus, @lastDate, @postedDate);

                clsobj.jobMsg = "Successfully inserted";
                return View("JobInsert_Pageload", clsobj);
            }
            return View("JobInsert_Pageload", clsobj);
        }
    }
}

JobPortalMVCApplication/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;


namespace JobPortalMVCApplication.Controllers
{
    public class LoginController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: Login
        public ActionResult Login_pageload()
        {
            return View();
        }
        public ActionResult login_click(LoginCls loginCls)
        {
            if (ModelState.IsValid)
            {
                var getId = dbobj.sp_CountLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                if (Convert.ToInt32(getId) == 1)
                {
                    var getRegId = dbobj.sp_GetLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                    Session["uid"] = getRegId;
                    string userType = dbobj.sp_LoginType(loginCls.username, loginCls.password).FirstOrDefault();
                    if (userType == "Company")
                    {
                        return RedirectToAction("AdminHome");
                    }
                    else if (userType == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    loginCls.msg = "INVALID USERNAME OR PASSWORD";
                    return View("Login_pageload", loginCls);
                }
            }
            return View("Login_pageload", loginCls);
        }
        public ActionResult AdminHome()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            var job = dbobj.tbl_Job.ToList();
            return View(job);
            //  var jobs=dbobj.sp_fetchAllJobDetails();
           // return View(jobs);
        }
    }
}

JobPortalMVCApplication/Views/Job/JobInsert_Pageload.cshtml
@model JobPortalMVCApplication.Models.InsertJobs
@{
    ViewBag.Title = "JobInsert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Job Details</h2>
<div>
    @using (Html.BeginForm("JobInsert_Click", "Job", FormMethod.Post))
    {
        <div>
            <label>Job Title:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobTitle)
            @Html.ValidationMessageFor(m => m.jobTitle)
        </div>
        <div>
            <label>Description::</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.jobDesp)
            @Html.ValidationMessageFor(m => m.jobDesp)
        </div>
        <div>
            <label>Skills Required:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.jobSkills)
            @Html.ValidationMessageFor(m => m.jobSkills)
        </div>
        <div>
            <label>Experience Required:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobExp)
            @Html.ValidationMessageFor(m => m.jobExp)
        </div>
        <div>
            <label>Salary Range:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobSalary)
            @Html.ValidationMessageFor(m => m.jobSalary)
        </div>
        <div>
            <label>Location:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobLoc)
            @Html.ValidationMessageFor(m => m.jobLoc)
        </div>
        <div>
            <label>Application last date:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobLastDate)
            @Html.ValidationMessageFor(m => m.jobLastDate)
        </div>
        <div>
            <label>Application Post date:</label>
        </div>
        <div>
            @Html.DisplayFor(m => m.jobPostedDate)
        </div>  
        <div>
            <label>Job Status:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.jobStatus)
            @Html.ValidationMessageFor(m => m.jobStatus)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.jobMsg)
        </div>
        <div>
            @Html.ActionLink("Go to Login", "Login_Pageload", "Login")
        </div>
    }
</div>
 