JobPortalMVCApplication/Controllers/JobSeekerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;

namespace JobPortalMVCApplication.Controllers
{
    public class JobSeekerController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: JobSeeker
        public ActionResult Jobseeker_PageLoad()
        {
            //dropdown list
            List<stclass> dropdownState = new List<stclass>
            {
                new stclass { sId = 1, sName = "Kerala" },
                new stclass { sId = 2, sName = "Karnataka" },
                new stclass { sId = 3, sName = "Assam" },
                new stclass { sId = 4, sName = "Tamil nadu" }
            };
            ViewBag.SelectedState = new SelectList(dropdownState, "sId", "sName");

            //checkbox list
            JobseekerRegistration clsobj = new JobseekerRegistration();
            clsobj.MyQualification = getQualificationData();
            return View(clsobj);
        }

        public List<Checkboxlist> getQualificationData()
        {
            List<Checkboxlist> qualification = new List<Checkboxlist>()
            {
                new Checkboxlist {Value="SSLC",Text="SSLC",IsChecked=true},
                 new Checkboxlist {Value="Plus Two",Text="Plus Two",IsChecked=false},
                  new Checkboxlist {Value="Btech",Text="Btech",IsChecked=false},
                   new Checkboxlist {Value="Mtech",Text="Mtech",IsChecked=false}
            };
            return qualification;
        }
        public ActionResult register_buttonClick(JobseekerRegistration clsobj, HttpPostedFileBase file, FormCollection form)
        {
            if(ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/Jobseeker Photos");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);
                    var fullpath = Path.Combine("~\\Jobseeker Photos", fname);
                    clsobj.photo = fullpath;
                }

                List<stclass> dropdownState = new List<stclass>
                 {
                new stclass { sId = 1, sName = "Kerala" },
                new stclass { sId = 2, sName = "Karnataka" },
                new stclass { sId = 3, sName = "Assam" },
                new stclass { sId = 4, sName = "Tamil nadu" }
                 };
                ViewBag.SelectedState = new SelectList(dropdownState, "sId", "sName");

                int selectedId = Convert.ToInt32(form["ddlstates"]);
                stclass selectedItem = dropdownState.FirstOrDefault(c => c.sId == selectedId);
                clsobj.sId = selectedItem.sId;
                clsobj.sName = selectedItem.sName;

                var quid = string.Join(",", clsobj.SelectedQual);
                clsobj.qual = quid;
                clsobj.MyQualification = getQualificationData();

                var getmaxid = dbobj.sp_MaxLoginId().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }

                dbobj.sp_RegisterJobSeeker(regid, clsobj.name, Convert.ToInt32(clsobj.age ), clsobj.address, clsobj.email, clsobj.phone, clsobj.gender, clsobj.sName, clsobj.qual, clsobj.skill, clsobj.exp, clsobj.location, clsobj.photo);
                dbobj.sp_InsertLoginCredentials(regid, clsobj.username, clsobj.password, "User");
                clsobj.msg = "Successfully Inserted";
                 return View("Jobseeker_PageLoad", clsobj);
             // return RedirectToAction("Login_pageload", "Login");

            }
            else
            {
                List<stclass> stList = new List<stclass>
                 {
                new stclass { sId = 1, sName = "Kerala" },
                new stclass { sId = 2, sName = "Karnataka" },
                new stclass { sId = 3, sName = "Assam" },
                new stclass { sId = 4, sName = "Tamil nadu" }
                 };
                ViewBag.SelectedState = new SelectList(stList, "sId", "sName");

                clsobj.MyQualification = getQualificationData();

                return View("Jobseeker_PageLoad", clsobj);

            }
        }

        


    }
}

JobPortalMVCApplication/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVCApplication.Models;


namespace JobPortalMVCApplication.Controllers
{
    public class LoginController : Controller
    {
        JobSearchMvcEntities dbobj = new JobSearchMvcEntities();
        // GET: Login
        public ActionResult Login_pageload()
        {
            return View();
        }
        public ActionResult login_click(LoginCls loginCls)
        {
            if (ModelState.IsValid)
            {
                var getId = dbobj.sp_CountLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                if (Convert.ToInt32(getId) == 1)
                {
                    var getRegId = dbobj.sp_GetLoginId(loginCls.username, loginCls.password).FirstOrDefault();
                    Session["uid"] = getRegId;
                    string userType = dbobj.sp_LoginType(loginCls.username, loginCls.password).FirstOrDefault();
                    if (userType == "Company")
                    {
                        return RedirectToAction("AdminHome");
                    }
                    else if (userType == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    loginCls.msg = "INVALID USERNAME OR PASSWORD";
                    return View("Login_pageload", loginCls);
                }
            }
            return View("Login_pageload", loginCls);
        }
        public ActionResult AdminHome()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            var job = dbobj.tbl_Job.ToList();
            return View(job);
            //  var jobs=dbobj.sp_fetchAllJobDetails();
           // return View(jobs);
        }
    }
}

JobPortalMVCApplication/Views/JobSeeker/Jobseeker_PageLoad.cshtml
@model JobPortalMVCApplication.Models.JobseekerRegistration
@{
    ViewBag.Title = "Jobseeker_PageLoad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>JOBSEEKER REGISTRATION</h2>
<div>
    @using (Html.BeginForm("register_buttonClick", "JobSeeker", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div><label>NAME :</label></div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>

        <div><label>AGE : :</label></div>
        <div>
            @Html.TextBoxFor(m => m.age)
            @Html.ValidationMessageFor(m => m.age)
        </div>

        <div><label>ADDRESS :</label></div>
        <div>
            @Html.TextAreaFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>

        <div><label>MAIL :</label></div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>

        <div><label>PHONE :</label></div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>

        <div><label>Qualification :</label></div>
        <div>
            @foreach (var item in Model.MyQualification)
            {
                <label>
                    <input type="checkbox" value="@item.Value" checked="@item.IsChecked" name="SelectedQual" id="@item.Value" />@Html.Raw(item.Text)
                </label>
            }
        </div>

        <div><label>GENDER :</label></div>
        <div>
            Male @Html.RadioButtonFor(m => m.gender, "Male")
            Female @Html.RadioButtonFor(m => m.gender, "Female")
        </div>

        <div><label>STATE :</label></div>
        <div>
            @Html.DropDownList("ddlstates", (SelectList)ViewBag.SelectedState, "--SELECT STATE--", new { @class = "form-Control" })
        </div>

        <div><label>SKILL :</label></div>
        <div>
            @Html.TextAreaFor(m => m.skill)
            @Html.ValidationMessageFor(m => m.skill)
        </div>

        <div><label>EXPERIENCE :</label></div>
        <div>
            @Html.TextBoxFor(m => m.exp)
            @Html.ValidationMessageFor(m => m.exp)
        </div>

        <div><label>LOCATION :</label></div>
        <div>
            @Html.TextBoxFor(m => m.location)
            @Html.ValidationMessageFor(m => m.location)
        </div>

        <div><label>PHOTO :</label></div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
            @Html.ValidationMessageFor(m => m.skill)
        </div>

        <div><label>USERNAME :</label></div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>

        <div><label>PASSWORD :</label></div>
        <div>
            @Html.PasswordFor(m => m.password)
            @Html.ValidationMessageFor(m => m.password)
        </div>
        <div><label>CONFIRM PASSWORD :</label></div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>

        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.msg)
        </div>
        <div>
            @Html.ActionLink("Go to Login", "Login_pageload", "Login")
        </div>



    }
</div>